 #
#baseurl: " " # the subpath of your site, e.g. /blog/
url: "http://www.dwnashville.com" # the base hostname & protocol for your site
site-url: "http://www.dwnashville.com"
gems:
  - jekyll
  - jekyll-sitemap

host: 0.0.0.0
# Build settings
markdown: kramdown

sass:
  sass_dir: _sass


description: "Design Works in Nashville Tenneesee offers high quality solid surface and laminate countertops for the bathroom and kitchen"
